export const SAVE_AUTH = "SAVE_AUTH";
export const SET_USER = "SET_USER";

export const START_LOADING_INDICATOR = "START_LOADING_INDICATOR";
export const STOP_LOADING_INDICATOR = "STOP_LOADING_INDICATOR";
